In [3]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable

In [8]:
import torch
channels = 3
x = torch.rand(100, channels, 784)
x_2d = torch.rand(1, channels, 7, 7)

bn_layer = torch.nn.BatchNorm1d(channels)
bn_layer_2d = torch.nn.BatchNorm2d(channels)

out = bn_layer(x)
out_2d = bn_layer_2d(x_2d)

print(bn_layer.running_mean)
print(bn_layer.running_var)

print(out.max(), out.min())
print(bn_layer_2d.weight)
print(bn_layer_2d.bias)

tensor([0.0501, 0.0500, 0.0501])
tensor([0.9083, 0.9083, 0.9083])
tensor(1.7313, grad_fn=<MaxBackward1>) tensor(-1.7402, grad_fn=<MinBackward1>)
Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
