In [3]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable

In [4]:
x = torch.rand(100, 16, 784)

layer = torch.nn.BatchNorm1d(16)
out = layer(x)

print(layer.running_mean)
print(layer.running_var)

print(out.max(), out.min())

tensor([0.0501, 0.0498, 0.0500, 0.0499, 0.0500, 0.0502, 0.0501, 0.0499, 0.0501,
        0.0502, 0.0501, 0.0498, 0.0501, 0.0501, 0.0500, 0.0501])
tensor([0.9084, 0.9083, 0.9083, 0.9083, 0.9083, 0.9084, 0.9083, 0.9083, 0.9084,
        0.9083, 0.9084, 0.9084, 0.9083, 0.9083, 0.9083, 0.9084])
tensor(1.7371, grad_fn=<MaxBackward1>) tensor(-1.7396, grad_fn=<MinBackward1>)


In [5]:
##2D
x = torch.rand(1, 16, 7, 7)
layer = torch.nn.BatchNorm2d(16)
out = layer(x)

print(layer.weight, layer.bias)

#print(vars(layer))
layer.eval()


Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True) Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)


BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)