In [8]:
import tensorflow as tf
print(tf.__version__)
print(len(tf.config.list_physical_devices('GPU')) == 0)

2.4.1
True


In [15]:
mammal = tf.Variable("Elephant", tf.string)
print(mammal)
tf.print(tf.rank(mammal))
tf.print(tf.shape(mammal))

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>
0
[]


In [26]:
tensor = tf.Variable([[1., 2., 3., 4.], [1., 2., 3., 4.], [1., 2., 3., 4.], [1., 2., 3., 4.]])
print(tensor)
print(tensor.numpy())

tf.print(tensor)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]], dtype=float32)>
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [31]:
tensor = tf.Variable([[1., 2., 3., 4.], [1., 2., 3., 4.], [1., 2., 3., 4.], [1., 2., 3., 4.]])
tf.print(tf.rank(tensor))
tf.print(tf.shape(tensor))

2
[4 4]


In [33]:
tensor = tf.constant([1,2,3], dtype=tf.int32) #常数
tf.print(tf.rank(tensor))
tf.print(tf.shape(tensor))

1
[3]


In [42]:
a = tf.random.uniform((10, 10)) # (10, 10)
tf.debugging.assert_equal(x=a.shape, y=(10, 10))
#tf.debugging.assert_equal(x=a.shape, y=(5, 10)) #错误示范

In [43]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

tf.print(tf.math.add(a,b))
tf.print(tf.math.subtract(a,b))
tf.print(tf.math.multiply(a,b))
tf.print(tf.math.divide(a,b))

[[6 8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[5 12]
 [21 32]]
[[0.2 0.33333333333333331]
 [0.42857142857142855 0.5]]


In [44]:
x =tf.constant([1.8, 2.2], dtype=tf.float32)
x1 = tf.dtypes.cast(x,tf.int32)
print(x1.dtype)

<dtype: 'int32'>
